# Generated by Django 5.1.7 on 2025-07-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='orderid',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
